apiVersion: v1
kind: Secret
metadata:
  name: external-scrape-configs
stringData:
  configs.yaml: |
    - job_name: 'external-vms'
      http_sd_configs:
        - url: 'http://network-prometheus-sd.monitoring.svc.cluster.local:8080/targets'
          refresh_interval: 30s
