apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    cert-manager.io/cluster-issuer: "stefanmuraru-com-issuer"
    external-dns.alpha.kubernetes.io/hostname: prometheus.monitoring.stefanmuraru.com
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: private
  tls:
    - hosts:
        - prometheus.monitoring.stefanmuraru.com
      secretName: prometheus-tls
  rules:
    - host: prometheus.monitoring.stefanmuraru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090