apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - https://raw.githubusercontent.com/murarustefaan/prometheus-sd-ipnet/refs/heads/main/deploy/manifests.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: network-prometheus-sd
      spec:
        template:
          spec:
            containers:
              - name: network-prometheus-sd
                env:
                  - name: NETWORK
                    value: 10.0.4.0/23